all:
  hosts:
    node1:
      ansible_host: 10.0.51.150
      ip: 10.0.51.150
      access_ip: 10.0.51.150
    node2:
      ansible_host: 10.0.51.160
      ip: 10.0.51.160
      access_ip: 10.0.51.160
    node3:
      ansible_host: 10.0.51.161
      ip: 10.0.51.161
      access_ip: 10.0.51.161
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
